[tool.pyright]
include = ["storage_inspect", "homebrew-tools", "npjm"]
exclude = [
  "**/__pycache__"
]
ignore = [
]

defineConstant = { DEBUG = true }
venv = "nexthack"

reportMissingImports = true

pythonVersion = "3.11"
pythonPlatform = "Darwin"

executionEnvironments = [
  { root = "storage_inspect" },
  { root = "homebrew-tools" },
  { root = "npjm" }
]
